--DDL
CREATE DATABASE CASHINOUT;

USE CASHINOUT;

CREATE TABLE CASHINOUT.dbo.USUARIO (
    ID int IDENTITY(1,1) PRIMARY KEY,
    IDENTIFICACION varchar(15) UNIQUE NOT NULL,
    NOMBRES varchar(50) NOT NULL,
    APELLIDOS varchar(50) NOT NULL,
    CLAVE varchar(255) NOT NULL,
    SEXO varchar(1) NOT NULL,
    FECHANACIMIENTO DATE NOT NULL,
    DIRECCION varchar(100) NOT NULL,
    TELEFONO varchar(12) NOT NULL,
    ESTADO bit NOT NULL DEFAULT 1,
    FCREACION datetime DEFAULT getdate() NOT NULL,
    FACTUALIZACION datetime NULL,
    UCREACION varchar(15) NOT NULL,
    UACTUALIZACION varchar(15)
);

CREATE TABLE CASHINOUT.dbo.TIPOCUENTA (
    ID int IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    FCREACION datetime DEFAULT getdate() NOT NULL,
    FACTUALIZACION datetime NULL,
    UCREACION varchar(15) NOT NULL,
    UACTUALIZACION varchar(15)
);

CREATE TABLE CASHINOUT.dbo.CUENTA (
	ID int IDENTITY(1,1) PRIMARY KEY,
    NUMEROCUENTA varchar(20) UNIQUE,
    IDUSUARIO int NOT NULL,
    IDTIPOCUENTA int NOT NULL,
    SALDO NUMERIC(12,2) NOT NULL DEFAULT 0,
    ESTADO bit NOT NULL DEFAULT 1,
    FCREACION datetime DEFAULT getdate() NOT NULL,
    FACTUALIZACION datetime NULL,
    UCREACION varchar(15) NOT NULL,
    UACTUALIZACION varchar(15),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (IDTIPOCUENTA) REFERENCES TIPOCUENTA(ID)
);

CREATE TABLE CASHINOUT.dbo.TIPOMOVIMIENTO (
    ID int IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION VARCHAR(50),
    FCREACION datetime DEFAULT getdate() NOT NULL,
    FACTUALIZACION datetime NULL,
    UCREACION varchar(15) NOT NULL,
    UACTUALIZACION varchar(15)
);

CREATE TABLE CASHINOUT.dbo.MOVIMIENTO (
    ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDCUENTA int NOT NULL,
    IDTIPOMOVIMIENTO int NOT NULL,
    FECHA datetime NOT NULL,
    VALOR NUMERIC(12,2) NOT NULL,
    SALDO NUMERIC(12,2) NOT NULL,
    FCREACION datetime DEFAULT getdate() NOT NULL,
    FACTUALIZACION datetime NULL,
    UCREACION varchar(15) NOT NULL,
    UACTUALIZACION varchar(15),
    FOREIGN KEY (IDCUENTA) REFERENCES CUENTA(ID),
    FOREIGN KEY (IDTIPOMOVIMIENTO) REFERENCES TIPOMOVIMIENTO(ID)
);

--DML

INSERT INTO CASHINOUT.dbo.TIPOCUENTA (DESCRIPCION, UCREACION)
VALUES 
('CTA. CORRIENTE', 'admin'),
('CTA. AHORROS', 'admin');


CREATE OR ALTER TRIGGER trg_GenerarNumeroCuenta
ON CASHINOUT.dbo.CUENTA
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE CUENTA
    SET NUMEROCUENTA = 
        CAST(i.IDTIPOCUENTA AS VARCHAR(1)) + -- Primer número: tipo cuenta
        RIGHT('0000' + CAST(i.ID AS VARCHAR(4)), 4) -- Secuencial del ID de la cuenta
    FROM INSERTED i
    WHERE CUENTA.ID = i.ID;
END;

INSERT INTO CASHINOUT.dbo.TIPOMOVIMIENTO (DESCRIPCION, UCREACION)
VALUES
('DEPÓSITO', 'admin'),
('RETIRO', 'admin');

INSERT INTO CASHINOUT.dbo.USUARIO (IDENTIFICACION, NOMBRES, APELLIDOS, CLAVE, SEXO, FECHANACIMIENTO, DIRECCION, TELEFONO, ESTADO, FCREACION, UCREACION, UACTUALIZACION) 
VALUES ('1234567890', 'Jose', 'Lema', '1234', 'M', '1990-01-01', 'Otavalo sn y principal', '098254785', 1, GETDATE(), 'admin', NULL);

INSERT INTO CASHINOUT.dbo.USUARIO (IDENTIFICACION, NOMBRES, APELLIDOS, CLAVE, SEXO, FECHANACIMIENTO, DIRECCION, TELEFONO, ESTADO, FCREACION, UCREACION, UACTUALIZACION) 
VALUES ('2345678901', 'Marianela', 'Montalvo', '5678', 'F', '1992-02-02', 'Amazonas y NNUU', '097548965', 1, GETDATE(), 'admin', NULL);

INSERT INTO CASHINOUT.dbo.USUARIO (IDENTIFICACION, NOMBRES, APELLIDOS, CLAVE, SEXO, FECHANACIMIENTO, DIRECCION, TELEFONO, ESTADO, FCREACION, UCREACION, UACTUALIZACION) 
VALUES ('3456789012', 'Juan', 'Osorio', '1245', 'M', '1994-03-03', '13 junio y Equinoccial', '098874587', 1, GETDATE(), 'admin', NULL);


-- Jose Lema - Ahorro
INSERT INTO CASHINOUT.dbo.CUENTA (IDUSUARIO, IDTIPOCUENTA, SALDO, ESTADO, FCREACION, UCREACION)
VALUES (1, 2, 2000, 1, GETDATE(), 'admin');

-- Marianela Montalvo - Corriente
INSERT INTO CASHINOUT.dbo.CUENTA (IDUSUARIO, IDTIPOCUENTA, SALDO, ESTADO, FCREACION, UCREACION)
VALUES (2, 1, 100, 1, GETDATE(), 'admin');

-- Juan Osorio - Ahorros
INSERT INTO CASHINOUT.dbo.CUENTA (IDUSUARIO, IDTIPOCUENTA, SALDO, ESTADO, FCREACION, UCREACION)
VALUES (3, 2, 0, 1, GETDATE(), 'admin');

-- Marianela Montalvo - Ahorros
INSERT INTO CASHINOUT.dbo.CUENTA (IDUSUARIO, IDTIPOCUENTA, SALDO, ESTADO, FCREACION, UCREACION)
VALUES (2, 2, 540, 1, GETDATE(), 'admin');


